---
title: "Correlations"
author: "Hector Kroes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE, fig.width=10, fig.height=10, fig.fullwidth=TRUE}
library(ggplot2)
library(ggpubr)

# Reading LUSC FPKM files
LUSC_SWINGN_FPKM = read.delim("LUSC_SWINGN_FPKM.txt", header = FALSE, stringsAsFactors = FALSE, quote = "", sep = "\t")
LUSC_GAS6_FPKM = read.delim("LUSC_GAS6_FPKM.txt", header = FALSE, stringsAsFactors = FALSE, quote = "", sep = "\t")
LUSC_PDGFRB_FPKM = read.delim("LUSC_PDGFRB_FPKM.txt", header = FALSE, stringsAsFactors = FALSE, quote = "", sep = "\t")
LUSC_COL1A1_FPKM = read.delim("LUSC_COL1A1_FPKM.txt", header = FALSE, stringsAsFactors = FALSE, quote = "", sep = "\t")

# Calculating LUSC pseudocounts
LUSC_SWINGN_pc = as.numeric(min(LUSC_SWINGN_FPKM[LUSC_SWINGN_FPKM['V2']>0]))
LUSC_GAS6_pc = as.numeric(min(LUSC_GAS6_FPKM[LUSC_GAS6_FPKM['V2']>0]))
LUSC_PDGFRB_pc = as.numeric(min(LUSC_PDGFRB_FPKM[LUSC_PDGFRB_FPKM['V2']>0]))
LUSC_COL1A1_pc = as.numeric(min(LUSC_COL1A1_FPKM[LUSC_COL1A1_FPKM['V2']>0]))

# Organizing LUSC data in dataframe
LUSC_FPKM <- data.frame(SWINGN = as.numeric(unlist(LUSC_SWINGN_FPKM['V2']))+LUSC_SWINGN_pc,
                        GAS6 = as.numeric(unlist(LUSC_GAS6_FPKM['V2']))+LUSC_GAS6_pc,
                        PDGFRB = as.numeric(unlist(LUSC_PDGFRB_FPKM['V2']))+LUSC_PDGFRB_pc, 
                        COL1A1 = as.numeric(unlist(LUSC_COL1A1_FPKM['V2']))+LUSC_COL1A1_pc)

# Reading BRCA FPKM files
BRCA_SWINGN_FPKM = read.delim("BRCA_SWINGN_FPKM.txt", header = FALSE, stringsAsFactors = FALSE, quote = "", sep = "\t")
BRCA_GAS6_FPKM = read.delim("BRCA_GAS6_FPKM.txt", header = FALSE, stringsAsFactors = FALSE, quote = "", sep = "\t")

# Calculating BRCA pseudocounts
BRCA_SWINGN_pc = as.numeric(min(BRCA_SWINGN_FPKM[BRCA_SWINGN_FPKM['V2']>0]))
BRCA_GAS6_pc = as.numeric(min(BRCA_GAS6_FPKM[BRCA_GAS6_FPKM['V2']>0]))

# Organizing BRCA data in dataframe
BRCA_FPKM <- data.frame(SWINGN = as.numeric(unlist(BRCA_SWINGN_FPKM['V2']))+BRCA_SWINGN_pc,
                        GAS6 = as.numeric(unlist(BRCA_GAS6_FPKM['V2']))+BRCA_GAS6_pc)

# Reading LUAD FPKM files
LUAD_SWINGN_FPKM = read.delim("LUAD_SWINGN_FPKM.txt", header = FALSE, stringsAsFactors = FALSE, quote = "", sep = "\t")
LUAD_GAS6_FPKM = read.delim("LUAD_GAS6_FPKM.txt", header = FALSE, stringsAsFactors = FALSE, quote = "", sep = "\t")

# Calculating LUAD pseudocounts
LUAD_SWINGN_pc = as.numeric(min(LUAD_SWINGN_FPKM[LUAD_SWINGN_FPKM['V2']>0]))
LUAD_GAS6_pc = as.numeric(min(LUAD_GAS6_FPKM[LUAD_GAS6_FPKM['V2']>0]))

# Organizing LUAD data in dataframe
LUAD_FPKM <- data.frame(SWINGN = as.numeric(unlist(LUAD_SWINGN_FPKM['V2']))+LUAD_SWINGN_pc,
                        GAS6 = as.numeric(unlist(LUAD_GAS6_FPKM['V2']))+LUAD_GAS6_pc)

# Reading PRAD FPKM files
PRAD_SWINGN_FPKM = read.delim("PRAD_SWINGN_FPKM.txt", header = FALSE, stringsAsFactors = FALSE, quote = "", sep = "\t")
PRAD_GAS6_FPKM = read.delim("PRAD_GAS6_FPKM.txt", header = FALSE, stringsAsFactors = FALSE, quote = "", sep = "\t")

# Calculating PRAD pseudocounts
PRAD_SWINGN_pc = as.numeric(min(PRAD_SWINGN_FPKM[PRAD_SWINGN_FPKM['V2']>0]))
PRAD_GAS6_pc = as.numeric(min(PRAD_GAS6_FPKM[PRAD_GAS6_FPKM['V2']>0]))

# Organizing PRAD data in dataframe
PRAD_FPKM <- data.frame(SWINGN = as.numeric(unlist(PRAD_SWINGN_FPKM['V2']))+PRAD_SWINGN_pc,
                        GAS6 = as.numeric(unlist(PRAD_GAS6_FPKM['V2']))+PRAD_GAS6_pc)

# Reading COAD FPKM files
COAD_SWINGN_FPKM = read.delim("COAD_SWINGN_FPKM.txt", header = FALSE, stringsAsFactors = FALSE, quote = "", sep = "\t")
COAD_GAS6_FPKM = read.delim("COAD_GAS6_FPKM.txt", header = FALSE, stringsAsFactors = FALSE, quote = "", sep = "\t")

# Calculating COAD pseudocounts
COAD_SWINGN_pc = as.numeric(min(COAD_SWINGN_FPKM[COAD_SWINGN_FPKM['V2']>0]))
COAD_GAS6_pc = as.numeric(min(COAD_GAS6_FPKM[COAD_GAS6_FPKM['V2']>0]))

# Organizing COAD data in dataframe
COAD_FPKM <- data.frame(SWINGN = as.numeric(unlist(COAD_SWINGN_FPKM['V2']))+COAD_SWINGN_pc,
                        GAS6 = as.numeric(unlist(COAD_GAS6_FPKM['V2']))+COAD_GAS6_pc)

LUSC_SWINGN_GAS6_plot <- ggplot(LUSC_FPKM, aes(x=log2(SWINGN), y=log2(GAS6))) + geom_point() + theme_grey(base_size = 10) +
  stat_cor(method="pearson", p.accuracy=1e-100, label.sep='\n')

LUSC_SWINGN_PDGFRB_plot <- ggplot(LUSC_FPKM, aes(x=log2(SWINGN), y=log2(PDGFRB))) + geom_point() + theme_grey(base_size = 10) +
  stat_cor(method="pearson", p.accuracy=1e-100, label.sep='\n')

LUSC_SWINGN_COL1A1_plot <- ggplot(LUSC_FPKM, aes(x=log2(SWINGN), y=log2(COL1A1))) + geom_point() + theme_grey(base_size = 10) +
  stat_cor(method="pearson", p.accuracy=1e-100, label.sep='\n')

LUSC_plots <- ggarrange(LUSC_SWINGN_GAS6_plot, LUSC_SWINGN_PDGFRB_plot, LUSC_SWINGN_COL1A1_plot)
ggsave('LUSC.png', LUSC_plots)
LUSC_plots

BRCA_SWINGN_GAS6_plot <- ggplot(BRCA_FPKM, aes(x=log2(SWINGN), y=log2(GAS6))) + geom_point() + theme_grey(base_size = 10)+
  stat_cor(method="pearson", p.accuracy=1e-100, label.sep='\n') +
  labs(title = "TCGA-BRCA", x = expression(paste("SWINGN [", log[2](FPKM), "]")), y = expression(paste("GAS6 [", log[2](FPKM), "]")))

LUAD_SWINGN_GAS6_plot <- ggplot(LUAD_FPKM, aes(x=log2(SWINGN), y=log2(GAS6))) + geom_point() + theme_grey(base_size = 10) +
  stat_cor(method="pearson", p.accuracy=1e-100, label.sep='\n') +
  labs(title = "TCGA-LUAD", x = expression(paste("SWINGN [", log[2](FPKM), "]")), y = expression(paste("GAS6 [", log[2](FPKM), "]")))

PRAD_SWINGN_GAS6_plot <- ggplot(PRAD_FPKM, aes(x=log2(SWINGN), y=log2(GAS6))) + geom_point() + theme_grey(base_size = 10) +
  stat_cor(method="pearson", p.accuracy=1e-100, label.sep='\n') +
  labs(title = "TCGA-PRAD", x = expression(paste("SWINGN [", log[2](FPKM), "]")), y = expression(paste("GAS6 [", log[2](FPKM), "]")))

COAD_SWINGN_GAS6_plot <- ggplot(COAD_FPKM, aes(x=log2(SWINGN), y=log2(GAS6))) + geom_point() + theme_grey(base_size = 10) +
  stat_cor(method="pearson", p.accuracy=1e-100, label.sep='\n') +
  labs(title = "TCGA-COAD", x = expression(paste("SWINGN [", log[2](FPKM), "]")), y = expression(paste("GAS6 [", log[2](FPKM), "]")))

GAS6_plots <- ggarrange(BRCA_SWINGN_GAS6_plot, LUAD_SWINGN_GAS6_plot, PRAD_SWINGN_GAS6_plot, COAD_SWINGN_GAS6_plot)
ggsave('GAS6.png', GAS6_plots)
GAS6_plots
```
